CREATE TABLE IF NOT EXISTS habitats
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    biome       VARCHAR(40)  NOT NULL,
    location    VARCHAR(120) NOT NULL,
    min_temp_c  INT          NOT NULL,
    max_temp_c  INT          NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_habitats PRIMARY KEY (id)
    );
