CREATE TABLE observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creature_id BIGINT NOT NULL,
    note TEXT NOT NULL,
    observed_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_observations_creature
        FOREIGN KEY (creature_id) REFERENCES creatures(id)
);