CREATE TABLE feeding_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creature_id BIGINT NOT NULL,
    feed_time TIMESTAMP NOT NULL,
    notes TEXT,

    CONSTRAINT fk_feeding_creature
        FOREIGN KEY (creature_id) REFERENCES creatures(id)
);