CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name VARCHAR(120) NOT NULL,
                       email VARCHAR(120) NOT NULL UNIQUE,
                       phone VARCHAR(20),
                       role_id BIGINT NOT NULL,

                       CONSTRAINT fk_users_role
                           FOREIGN KEY (role_id) REFERENCES roles(id)
);

INSERT INTO roles (name) VALUES
                             ('ADMIN'),
                             ('STAFF');

INSERT INTO users (full_name, email, phone, role_id) VALUES
                                                         ('Mercy Mercedes', 'mercy@neonark.com', '123-456-7890', 1),
                                                         ('Junkrat Jones', 'junkrat@neonark.com', '555-123-4567', 2);